### ISSUE TITLE
容器启动后一直重启

### ISSUE THREAD

**Issue by kaaaaai** [z-mio/Alist-bot#11]
如题，有解法吗？

**Comment by z-mio** [comment]
检查一下配置文件, 代理和alist的配置填对没

**Comment by kaaaaai** [comment]
> reply

有什么方式可以看到 bot 的日志吗？

**Comment by z-mio** [comment]
docker logs -f alist-bot

**Comment by kaaaaai** [comment]
> reply

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/32ebcfce-9f9f-40d6-b385-073e329d776c">

是不是和我的机子是国外的有关系？

**Comment by z-mio** [comment]
国外的就不用填代理, 把代理的配置改成空格就行

```
proxy:
  hostname: 
  port: 
  scheme: 

```

**Comment by kaaaaai** [comment]
> 国外的就不用填代理, 把代理的配置改成空格就行
> 
> ```
> proxy:
>   hostname: 
>   port: 
>   scheme: 
> ```

<img width="1332" alt="image" src="https://github.com/user-attachments/assets/d5eca857-4cce-4490-91b0-48cd326fe04b">

还是有些问题😂

**Comment by z-mio** [comment]
alist的索引开了吗, 可以搜到东西吗

**Comment by kaaaaai** [comment]
@z-mio 

开了后网页 alist 可以搜到，tg 报错变了

<img width="1398" alt="image" src="https://github.com/user-attachments/assets/b4b3a056-2b3f-4ae1-a2e6-9bb08a4ee867">

**Comment by z-mio** [comment]
重启bot

**Comment by kaaaaai** [comment]
> 重启bot

重启可以，但好像一用图床功能就会报上面的错误

**Comment by kaaaaai** [comment]
另外想问下，如何将下载文件指定文件夹？

**Comment by z-mio** [comment]
> 另外想问下，如何将下载文件指定文件夹？

`config/config.py` 里面改
