### ISSUE TITLE
无法获取链接
一直卡在这里

### ISSUE THREAD

**Issue by lqbby** [z-mio/Alist-bot#2]
![IMG_20230507_152252.jpg](https://user-images.githubusercontent.com/93820952/236663777-7d43fa5d-b8e7-4406-bdb5-dc6c3631d4be.jpg)

**Comment by z-mio** [comment]
已优化

**Comment by lqbby** [comment]
![微信截图_20230507173806](https://user-images.githubusercontent.com/93820952/236669820-24cf84b0-5d44-4b89-a8e6-858975cd7d1a.png)
储存管理也报错了
还是无法获取链接

**Comment by z-mio** [comment]
已修复

**Comment by lqbby** [comment]
已经解决链接路径有emoji表情，删掉就可以了
