### ISSUE TITLE
使用/s命令后台报错

### ISSUE THREAD

**Issue by Synchronized1** [z-mio/Alist-bot#3]
你好,作者,我在使用过程中遇到如下问题,请问该如何解决? 😄 
python版本:
![image](https://github.com/z-mio/Alist-bot/assets/58451554/749dee18-b116-4d4b-a442-7103bd689f1d)
报错界面:
![image](https://github.com/z-mio/Alist-bot/assets/58451554/62678f3c-1fb7-46fd-8c3a-3242f0509e82)
![image](https://github.com/z-mio/Alist-bot/assets/58451554/921783f2-afde-4a3c-9ea6-dbb8b5b75780)

**Comment by z-mio** [comment]
alist的索引打开了吗

**Comment by Synchronized1** [comment]
> alist的索引打开了吗
已成功,感谢大佬指点🤭
