### ISSUE TITLE
请问开启直链的问题？

### ISSUE THREAD

**Issue by reyfull** [z-mio/Alist-bot#5]
请问开启直链是网盘本来就有302功能才能开启直链的意思吗？
还是任何网盘都能开启直链的功能,如谷歌网盘也可以开启直链吗,谢谢

**Comment by z-mio** [comment]
都可以开启，这个获取直链是在搜索结果上显示文件的下载链接，方便直接下载，不用再跳转到网页
![](https://i.miji.bid/2023/11/30/e145a022253f1bbab054dac8f522b361.png)

**Comment by reyfull** [comment]
再请问一下,搜索是要先在alist建立索引吗？
我搜索在alist已建立的存储并没有任何反应,譬如输入 /s test 机器人没有反应（alist存储上有这个文件名）
服务器出现以下讯息：
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/Alist-bot/module/search.py", line 53, in s
    if not alist_post_json['data']['content']:
TypeError: 'NoneType' object is not subscriptable

**Comment by z-mio** [comment]
要先建立索引，bot调用的alist api

**Comment by reyfull** [comment]
> 若要先建立索引，bot呼叫的alist api

已经搜索有反应了,谢谢
