### ISSUE TITLE
  alist_web和alist_token是什么呀？

### ISSUE THREAD

**Issue by caicaiacai** [z-mio/Alist-bot#6]
alist_web: "https://" # 你的alist域名
  alist_token: "" # alist token

这两个不知道怎么弄呀

**Comment by z-mio** [comment]
alist web就是你alist的域名，没有域名就填ip+端口
alist token在alist后台里面 设置 - 其他 - 令牌

**Comment by caicaiacai** [comment]
谢谢，，然后bot.py里emus找不到，，我又重新弄了个环境，，然后现在apt install python3-pip一直安装不上，，，提示E: Unable to locate package python3-pip，，哭辽，，弄了好久好久了

**Comment by caicaiacai** [comment]
我查询是pyrogram2.x支持enums，但是不支持BotCommand ( from pyrogram.types import BotCommand, Message这一行)
然后3.x支持BotCommand，但没有enums。。。。。

**Comment by z-mio** [comment]
更新 python 版本到 3.10 再重装 pyrogram 试试

**Comment by caicaiacai** [comment]
python3.10以上，可以了，，但是ubuntu上挂不上节点。。。。。大佬有什么挂节点的办法么？折腾了qv2ray,,clash都没成功，，，换windows系统就可以翻出去了。。

**Comment by z-mio** [comment]
没有哦，建议用海外服务器挂bot

**Comment by caicaiacai** [comment]
![11](https://github.com/z-mio/Alist-bot/assets/80669183/ac491fb3-99a0-4689-9016-989cc0542a47)
![111](https://github.com/z-mio/Alist-bot/assets/80669183/192cb1c7-e0a2-4a6b-8ce5-3e464bda9b28)
大佬，，好像搜索文件的话循环报这个，，，，是我哪里没弄对么？Orz

**Comment by z-mio** [comment]
Alist后台建立索引了吗
